from TP2.src.bellman_ford import BellmanFord
from TP2.src.grafo import Grafo

g = Grafo()
g.agregar_vertice(1)
g.agregar_vertice(2)
g.agregar_vertice(3)
g.agregar_vertice(4)
g.agregar_vertice(5)
g.agregar_arista_dirigida(1, 2, 6)
g.agregar_arista_dirigida(1, 4, 7)
g.agregar_arista_dirigida(2, 3, 5)
g.agregar_arista_dirigida(2, 4, 8)
g.agregar_arista_dirigida(2, 5, -4)
g.agregar_arista_dirigida(3, 2, -2)
g.agregar_arista_dirigida(4, 3, -3)
g.agregar_arista_dirigida(4, 5, 9)
g.agregar_arista_dirigida(5, 1, 2)
g.agregar_arista_dirigida(5, 3, 7)
d = BellmanFord(g)
print "Nodo 1\n", d.bellmanFord(1)
print "Nodo 2\n", d.bellmanFord(2)
print "Nodo 3\n", d.bellmanFord(3)
print "Nodo 4\n", d.bellmanFord(4)
print "Nodo 5\n", d.bellmanFord(5)
