from TP2.src.dijkstra import Dijkstra
from TP2.src.grafo import Grafo

g = Grafo()
g.agregar_vertice(1)
g.agregar_vertice(2)
g.agregar_vertice(3)
g.agregar_vertice(4)
g.agregar_vertice(5)
g.agregar_vertice(6)
g.agregar_arista_no_dirigida(1, 2, 7)
g.agregar_arista_no_dirigida(1, 3, 9)
g.agregar_arista_no_dirigida(1, 6, 14)
g.agregar_arista_no_dirigida(2, 3, 10)
g.agregar_arista_no_dirigida(2, 4, 15)
g.agregar_arista_no_dirigida(3, 4, 11)
g.agregar_arista_no_dirigida(3, 6, 2)
g.agregar_arista_no_dirigida(4, 5, 6)
g.agregar_arista_no_dirigida(5, 6, 9)
d = Dijkstra(g)
print "Nodo 1\n", d.dijkstra(1)
print "Nodo 2\n", d.dijkstra(2)
print "Nodo 3\n", d.dijkstra(3)
print "Nodo 4\n", d.dijkstra(4)
print "Nodo 5\n", d.dijkstra(5)
print "Nodo 6\n", d.dijkstra(6)
