from TP2.src.floyd_warshall import FloydWarshall
from TP2.src.grafo import Grafo

g = Grafo()
g.agregar_vertice(1)
g.agregar_vertice(2)
g.agregar_vertice(3)
g.agregar_vertice(4)
g.agregar_vertice(5)
g.agregar_arista_dirigida(1, 2, 3)
g.agregar_arista_dirigida(1, 3, 8)
g.agregar_arista_dirigida(1, 5, -4)
g.agregar_arista_dirigida(2, 4, 1)
g.agregar_arista_dirigida(2, 5, 7)
g.agregar_arista_dirigida(3, 2, 4)
g.agregar_arista_dirigida(4, 1, 2)
g.agregar_arista_dirigida(4, 3, -5)
g.agregar_arista_dirigida(5, 4, 6)
d = FloydWarshall(g)
print "Matriz\n", d.floydWarshall()
