from TP2.src.floyd_warshall import FloydWarshall
from TP2.src.grafo import Grafo

g = Grafo()
g.agregar_vertice(0)
g.agregar_vertice(1)
g.agregar_vertice(2)
g.agregar_vertice(3)
g.agregar_vertice(4)
g.agregar_arista_dirigida(0, 1, 3)
g.agregar_arista_dirigida(0, 2, 8)
g.agregar_arista_dirigida(0, 4, -4)
g.agregar_arista_dirigida(1, 3, 1)
g.agregar_arista_dirigida(1, 4, 7)
g.agregar_arista_dirigida(2, 1, 4)
g.agregar_arista_dirigida(3, 0, 2)
g.agregar_arista_dirigida(3, 2, -5)
g.agregar_arista_dirigida(4, 3, 6)
fw = FloydWarshall(g)
print "Matriz\n", fw.floydWarshall()
